version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai-postgres
    environment:
      POSTGRES_DB: incidentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: